<a href="https://colab.research.google.com/github/chumbah/kidscareNGO/blob/main/avatarify.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Avatarify Colab Server

This Colab notebook is for running Avatarify rendering server. It allows you to run Avatarify on your computer **without GPU** in this way:

1. When this notebook is executed, it starts listening for incoming requests from your computer;
1. You start the client on your computer and it connects to the notebook and starts sending requests;
1. This notebooks receives the requests from your computer, renders avatar images and sends them back;

To this end, all the heavy work is offloaded from your computer to this notebook so you don't need to have a beafy hardware on your PC anymore.


## Start the server
Run the cells below (Shift+Enter) sequentially and pay attention to the hints and instructions included in this notebook.

At the end you will get a command for running the client on your computer.

## Start the client

Make sure you have installed the latest version of Avatarify on your computer. Refer to the [README](https://github.com/alievk/avatarify#install) for the instructions.

When it's ready execute this notebook and get the command for running the client on your computer.


### Technical details

The client on your computer connects to the server via `ngrok` TCP tunnel or a reverse `ssh` tunnel.

`ngrok`, while easy to use, can induce a considerable network lag ranging from dozens of milliseconds to a second. This can lead to a poor experience.

A more stable connection could be established using a reverse `ssh` tunnel to a host with a public IP, like an AWS `t3.micro` (free) instance. This notebook provides a script for creating a tunnel, but launching an instance in a cloud is on your own (find the manual below).

# Install

### Avatarify
Follow the steps below to clone Avatarify and install the dependencies.

In [25]:
!cd /content
!rm -rf *

In [26]:
!git clone https://github.com/alievk/avatarify.git

Cloning into 'avatarify'...
remote: Enumerating objects: 1514, done.
remote: Total 1514 (delta 0), reused 0 (delta 0), pack-reused 1514 (from 1)
Receiving objects: 100% (1514/1514), 5.69 MiB | 24.89 MiB/s, done.
Resolving deltas: 100% (967/967), done.


In [27]:
cd avatarify

/content/avatarify/avatarify/avatarify


In [28]:
!git clone https://github.com/alievk/first-order-model.git fomm
!pip install face-alignment==1.0.0 msgpack_numpy pyyaml==5.1

Cloning into 'fomm'...
remote: Enumerating objects: 211, done.
remote: Total 211 (delta 0), reused 0 (delta 0), pack-reused 211 (from 1)
Receiving objects: 100% (211/211), 58.16 MiB | 19.81 MiB/s, done.
Resolving deltas: 100% (108/108), done.
Updating files: 100% (44/44), done.
  Using cached face_alignment-1.0.0-py2.py3-none-any.whl.metadata (6.7 kB)
  Using cached PyYAML-5.1.tar.gz (274 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [29]:
!scripts/download_data.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  228M  100  228M    0     0   101M      0  0:00:02  0:00:02 --:--:--  101M
Expected checksum: 8a45a24037871c045fbb8a6a8aa95ebc
Found checksum:    8a45a24037871c045fbb8a6a8aa95ebc  vox-adv-cpk.pth.tar


### ngrok
Follow the steps below to setup ngrok. You will also need to sign up on the ngrok site and get your authtoken (free).


In [30]:
# Download ngrok
!scripts/get_ngrok.sh

ngrok is not found, installing...
Done!


# Run
Start here if the runtime was restarted after installation.

In [31]:
cd /content/avatarify

/content/avatarify


In [32]:
#!git pull origin

In [33]:
from subprocess import Popen, PIPE
import shlex
import json
import time


def run_with_pipe(command):
  commands = list(map(shlex.split,command.split("|")))
  ps = Popen(commands[0], stdout=PIPE, stderr=PIPE)
  for command in commands[1:]:
    ps = Popen(command, stdin=ps.stdout, stdout=PIPE, stderr=PIPE)
  return ps.stdout.readlines()


def get_tunnel_adresses():
  info = run_with_pipe("curl http://localhost:4040/api/tunnels")
  assert info

  info = json.loads(info[0])
  for tunnel in info['tunnels']:
    url = tunnel['public_url']
    port = url.split(':')[-1]
    local_port = tunnel['config']['addr'].split(':')[-1]
    print(f'{url} -> {local_port} [{tunnel["name"]}]')
    if tunnel['name'] == 'input':
      in_addr = url
    elif tunnel['name'] == 'output':
      out_addr = url
    else:
      print(f'unknown tunnel: {tunnel["name"]}')

  return in_addr, out_addr

In [34]:
# Input and output ports for communication
local_in_port = 5557
local_out_port = 5558

# Start the worker


In [35]:
# (Re)Start the worker
with open('/tmp/run.txt', 'w') as f:
  ps = Popen(
      shlex.split(f'./run.sh --is-worker --in-port {local_in_port} --out-port {local_out_port} --no-vcam --no-conda'),
      stdout=f, stderr=f)
  time.sleep(3)

This command should print lines if the worker is successfully started

In [36]:
!ps aux | grep 'python3 afy/cam_fomm.py' | grep -v grep | tee /tmp/ps_run
!if [[ $(cat /tmp/ps_run | wc -l) == "0" ]]; then echo "Worker failed to start"; cat /tmp/run.txt; else echo "Worker started"; fi

root       20391 44.0  1.0 3570400 145132 ?      Dl   21:45   0:01 python3 afy/cam_fomm.py --config fomm/config/vox-adv-256.yaml --checkpoint vox-adv-cpk.pth.tar --virt-cam 9 --relative --adapt_scale --is-worker --in-port 5557 --out-port 5558 --no-stream
Worker started


# Open ngrok tunnel

#### Get ngrok token
Go to https://dashboard.ngrok.com/auth/your-authtoken (sign up if required), copy your authtoken and put it below.

In [37]:
# Paste your authtoken here in quotes
authtoken = "2ygmbOzzqV0genJRZtnePKKcz2m_siQa76pwePcKfDh4ZfS1"

Set your region

Code | Region
--- | ---
us | United States
eu | Europe
ap | Asia/Pacific
au | Australia
sa | South America
jp | Japan
in | India

In [38]:
# Set your region here in quotes
region = "eu"

In [39]:
config =\
f"""
version: 2
authtoken: {authtoken}
region: {region}
console_ui: False
tunnels:
  input:
    addr: {local_in_port}
    proto: tcp
  output:
    addr: {local_out_port}
    proto: tcp
"""

with open('ngrok.conf', 'w') as f:
  f.write(config)

In [40]:
# (Re)Open tunnel
ps = Popen('./scripts/open_tunnel_ngrok.sh', stdout=PIPE, stderr=PIPE)
time.sleep(3)

In [41]:
# Get tunnel addresses
try:
  in_addr, out_addr = get_tunnel_adresses()
  print("Tunnel opened")
except Exception as e:
  [print(l.decode(), end='') for l in ps.stdout.readlines()]
  print("Something went wrong, reopen the tunnel")

https://63f1-34-75-51-179.ngrok-free.app -> 5000 [command_line]
unknown tunnel: command_line
Opening tunnel
Something went wrong, reopen the tunnel


### [Optional] AWS proxy
Alternatively you can create a ssh reverse tunnel to an AWS `t3.micro` instance (it's free). It has lower latency than ngrok.

1. In your AWS console go to Services -> EC2 -> Instances -> Launch Instance;
1. Choose `Ubuntu Server 18.04 LTS` AMI;
1. Choose `t3.micro` instance type and press Review and launch;
1. Confirm your key pair and press Launch instances;
1. Go to the security group of this instance and edit inbound rules. Add TCP ports 5557 and 5558 and set Source to Anywhere. Press Save rules;
1. ssh into the instance (you can find the command in the Instances if you click on the Connect button) and add this line in the end of `/etc/ssh/sshd_config`:
```
GatewayPorts yes
```
then restart `sshd`
```
sudo service sshd restart
```
1. Copy your `key_pair.pem` by dragging and dropping it into avatarify folder in this notebook;
1. Use the command below to open the tunnel;
1. Start client with a command (substitute `run_mac.sh` with `run_windows.bat` or `run.sh`)
```
./run_mac.sh --is-client --in-addr tcp://instace.compute.amazonaws.com:5557 --out-addr tcp://instance.compute.amazonaws.com:5558
```

In [42]:
# Open reverse ssh tunnel (uncomment line below)
# !./scripts/open_tunnel_ssh.sh key_pair.pem ubuntu@instance.compute.amazonaws.com

# Start the client
When you run the cell below it will print a command. Run this command on your computer:

1. Open a terminal (in Windows open `Anaconda Prompt`);
2. Change working directory to the `avatarify` directory:</br>
* Windows (change `C:\path\to\avatarify` to your path)</br>
`cd C:\path\to\avatarify`</br></br>
* Mac/Linux (change `/path/to/avatarify` to your path)</br>
`cd /path/to/avatarify`
3. Copy-paste to the terminal the command below and run;
4. It can take some time to connect (usually up to 10 seconds). If the preview window doesn't appear in a minute or two, look for the errors above in this notebook and report in the [issues](https://github.com/alievk/avatarify/issues) or [Slack](https://join.slack.com/t/avatarify/shared_invite/zt-dyoqy8tc-~4U2ObQ6WoxuwSaWKKVOgg).

In [43]:
# Install ngrok v3+ (new required version)
!wget -q -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
!unzip -o ngrok.zip
!chmod +x ngrok

# Authenticate (replace YOUR_TOKEN_HERE with your actual authtoken)
!./ngrok config add-authtoken 2ygmbOzzqV0genJRZtnePKKcz2m_siQa76pwePcKfDh4ZfS1


Archive:  ngrok.zip
  inflating: ngrok                   
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml


In [44]:
# Step 1: Clone Avatarify and setup
!git clone https://github.com/alievk/avatarify.git
%cd avatarify

# Step 2: Install requirements
!pip install -r requirements.txt
!pip install face_alignment msgpack_numpy

# Step 3: Install ngrok v3+
!wget -q -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
!unzip -o ngrok.zip
!chmod +x ngrok

# Step 4: Add ngrok authtoken (replace with yours)
!./ngrok config add-authtoken 2ygmbOzzqV0genJRZtnePKKcz2m_siQa76pwePcKfDh4ZfS1

# Step 5: Set correct Python path so afy/ is importable
import sys, time, urllib.request, json
from subprocess import Popen

sys.path.append('/content/avatarify')

# Step 6: Launch cam server in the background
cam_server = Popen(["python3", "afy/cam_fomm.py"])
time.sleep(4)  # Give it time to start

# Step 7: Open ngrok tunnel to port 5000
ngrok_proc = Popen(["./ngrok", "http", "5000"])
time.sleep(5)

# Step 8: Fetch public URL from ngrok
try:
    with urllib.request.urlopen("http://localhost:4040/api/tunnels") as url:
        data = json.loads(url.read().decode())
        public_url = data['tunnels'][0]['public_url']
        in_addr = out_addr = public_url
        print("✅ Ngrok Tunnel Opened:", public_url)
except Exception as e:
    print("❌ Failed to open ngrok tunnel:", e)
    in_addr = out_addr = None

# Step 9: Print client connection commands
if in_addr and out_addr:
    print("\nPaste the following into your Avatarify client terminal:\n")
    print("🔵 Mac:")
    print(f'./run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')
    print("\n🟢 Windows:")
    print(f'run_windows.bat --is-client --in-addr {in_addr} --out-addr {out_addr}')
else:
    print("❌ Tunnel or cam server not running.")


fatal: destination path 'avatarify' already exists and is not an empty directory.
/content/avatarify/avatarify
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Archive:  ngrok.zip
  inflating: ngrok                   
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
✅ Ngrok Tunnel Opened: https://63f1-34-75-51-179.ngrok-free.app

Paste the following into your Avatarify client terminal:

🔵 Mac:
./run_mac.sh --is-client --in-addr https://63f1-34-75-51-179.ngrok-free.app --out-addr https://63f1-34-75-51-179.ngrok-free.app

🟢 Windows:
run_windows.bat --is-client --in-addr https://63f1-34-75-51-179.ngrok-free.app --out-addr https://63f1-34-75-51-179.ngrok-free.app


In [45]:
!python3 afy/cam_fomm.py


python3: can't open file '/content/avatarify/avatarify/afy/cam_fomm.py': [Errno 2] No such file or directory


In [46]:
print('Copy-paste to the terminal the command below and run (press Enter)\n')
print('Mac:')
print(f'./run_mac.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')
print('\nWindows:')
print(f'run_windows.bat --is-client --in-addr {in_addr} --out-addr {out_addr}')
print('\nLinux:')
print(f'./run.sh --is-client --in-addr {in_addr} --out-addr {out_addr}')

Copy-paste to the terminal the command below and run (press Enter)

Mac:
./run_mac.sh --is-client --in-addr https://63f1-34-75-51-179.ngrok-free.app --out-addr https://63f1-34-75-51-179.ngrok-free.app

Windows:
run_windows.bat --is-client --in-addr https://63f1-34-75-51-179.ngrok-free.app --out-addr https://63f1-34-75-51-179.ngrok-free.app

Linux:
./run.sh --is-client --in-addr https://63f1-34-75-51-179.ngrok-free.app --out-addr https://63f1-34-75-51-179.ngrok-free.app


# Logs

If something doesn't work as expected, please run the cells below and include the logs in your report.

In [47]:
#@title
!cat ./var/log/cam_fomm.log | head -100

cat: ./var/log/cam_fomm.log: No such file or directory


In [48]:
#@title
!cat ./var/log/recv_worker.log | tail -100

cat: ./var/log/recv_worker.log: No such file or directory


In [49]:
#@title
!cat ./var/log/predictor_worker.log | tail -100

cat: ./var/log/predictor_worker.log: No such file or directory


In [50]:
#@title
!cat ./var/log/send_worker.log | tail -100

cat: ./var/log/send_worker.log: No such file or directory
